### ISSUE TITLE
thumb glow dosen't dissapre after I put of my hand from slider 

### ISSUE THREAD

**Issue by Abolfazl-MI** [suragch/audio_video_progress_bar#57] opened 2023-06-20 12:44 UTC
as example saied I using the package but when I touch the thumb glow and slide it after I put off my hand from screen the glow dosent dissapre

**Comment by suragch** [comment] 2023-06-26 03:16
Does this behavior happen for you with the example project included in the repository?

**Comment by suragch** [comment] 2023-08-24 06:42
I'm not able to reproduce this so I'm closing the issue for now.

**Closed by suragch** 2023-08-24 06:42 UTC
