### ISSUE TITLE
Circle does not move despite progress bar moving

### ISSUE THREAD

**Issue by schisms** [suragch/audio_video_progress_bar#9] opened 2021-05-01 20:38 UTC
I have the ProgressBar contained a stack, and it is set to only appear when my video is paused. On pause, the progress bar does reflect the time elapsed out the total time. The highlighted portion does indicate how much time has passed.

However, the circle "thumb" is always set at 0:00.

This issue only occurs when the ProgressBar is set to display when the video is paused. If I remove this condition, the circle does follow the time passed.

**Comment by schisms** [comment] 2021-05-01 21:43
Fixed by using Visibility widget to control appearance of widget, instead of a condition statement within the stack.

Note that the this only works if you use **maintainState: true** in the visibility widget.

**Comment by suragch** [comment] 2021-05-01 21:52
I haven't had this problem come up before. Thanks for sharing your solution. If you can share a minimally reproducible code example I could look at the cause and see if I could find a solution that doesn't require a visibility widget.

**Comment by suragch** [comment] 2021-07-20 03:16
This may be related to issue #12.

**Comment by suragch** [comment] 2021-07-30 06:40
Version 0.6.2 removes the need to maintain state, so `Visibility` no longer requires `maintainState: true`. I'm not sure how it affects your original issue with using conditionals. I think it might fix that too, since the initial thumb position is now based on the progress and total durations rather than 0.0.

**Comment by suragch** [comment] 2021-08-02 11:21
I'll close this issue for now but I can reopen it if there are any more problems related to it.

**Closed by suragch** 2021-08-02 11:21 UTC
