### ISSUE TITLE
onSeek Method NEVER work with the acc urls .. 

### ISSUE THREAD

**Issue by jack84156** [suragch/audio_video_progress_bar#36] opened 2022-04-19 22:25 UTC
non acc url format :  audioPlayer.setUrl('https://archive.org/download/IGM-V7/IGM%20-%20Vol.%207/25%20Diablo%20-%20Tristram%20%28Blizzard%29.mp3');
 onSeek: (u){
 audioPlayer.seek(u); // outputs :  fine 
 },

...

acc url format  :audioPlayer.setUrl('url');
 onSeek: (u){
 audioPlayer.seek(u); // outputs : always run the audio from beginning . 
 },

**Comment by thesensibledev** [comment] 2022-09-13 08:30
The Link results in a 302 Redirect pointing to a new location.  This redirection to the new resource is to be handle by the Audio Player plugin, and it seems like the issue has been fixed now. 
If the issue is still replicable, please specify the platform.

**Comment by suragch** [comment] 2022-10-07 05:54
I'm closing this issue for now, but if the problem still exists, please reopen it with directions on how to reproduce the problem.

**Closed by suragch** 2022-10-07 05:54 UTC
